version: "3.4"

services:
  recall-zipkin:
    ports:
      - "35411:9411"
    # SideCar for TextItem.Api

  recall-seq:
    environment:
      - ACCEPT_EULA=Y # End-User License Agreement(EULA) 最终用户许可协议
    ports:
      - "35340:80"

  recall-sqldata:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "35433:1433"
    volumes:
      # 这里是一个名为recall-sqldata的卷，用于存储数据库文件
      - recall-sqldata:/var/opt/mssql

  recall-textitemapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "5163:5163"
      # - "35210:80"
      - "50001"

  recall-textitemapi-dapr:
    command:
      [
        "./daprd",
        "-app-id",
        "recall-textitemapi",
        "-app-port",
        "5163",
        "-components-path",
        "/components",
        "-config",
        "/configuration/recall-configuration.yaml",
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

  recall-listapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5231:5231"

  recall-listapi-dapr:
    command:
      [
        "./daprd",
        "-app-id",
        "recall-listapi",
        "-app-port",
        "5231",
        "-components-path",
        "/components",
        "-config",
        "/configuration/recall-configuration.yaml",
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"

  recall-envoygateway:
    volumes:
      - ./Infrastructure/envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "35191:80" # 访问网关的访问地址
      - "35181:8001" # 访问envoy的管理地址，可以通过这个端口查看配置文件

  recall-envoygateway-dapr:
    command: [
        "./daprd",
        "-app-id",
        "recall-envoygateway",
        "-app-port",
        "80",
        "-components-path",
        "/components",
        # "-config",
        # "/configuration/recall-configuration.yaml",
      ]
    volumes:
      - "./dapr/components/:/components"
      # - "./dapr/configuration/:/configuration" # 老师的代码里面没有加这一行到底是怎么跑起来的？

  recall-servicestatus:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "35107:5231"

  recall-rabbitmq:
    ports:
      - "35672:5672"
      - "35673:15672"

# 声明一个名为recall-sqldata的卷
# sqlserver的数据文件会存储在这个卷中
volumes:
  recall-sqldata:
    external: false
