# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: "3.4"

services:
  recall-textitemapi:
    image: recall-textitemapi
    build:
      context: .
      dockerfile: Contrib/TextItem.Api/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5163:5163
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
